version: '3.7'

services:
  web:
    build: ./ms-django/app
    command: gunicorn ms_django.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./ms-django/.env.prod
    depends_on:
      - db_transactions_prod

  db_transactions_prod:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_transactions_prod:/var/lib/postgresql/data/
    env_file:
      - ./ms-django/.env.prod.db

volumes:
    postgres_data_transactions_prod: